changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "New features"
      labels:
        - enhancement
        - feature
    - title: "Bug fixes"
      labels:
        - bug
        - fix
    - title: "Installation & packaging"
      labels:
        - install
        - packaging
    - title: "Documentation"
      labels:
        - documentation
    - title: "Other changes"
      labels:
        - "*"
